Add content to index folder
WillyStorm/PortFolioMobile pull request #1
Opened 2022-03-21 08:28 UTC by WillyStorm

2022-03-21 10:30 UTC, mikethreels requested changes
Hi Willy, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-21 10:30 UTC, mikethreels commented on index.html
> +    <link rel="stylesheet" href="/style.css">
- [ ] please remove the forward-slash (/) from the `href` here because the style sheet is not loaded because of this.

2022-03-21 10:30 UTC, mikethreels commented on style.css
> +}
- [ ] there is empty space (see below image) on the sides of the application, you can fix this by changing the `margin` to "0" and removing the `max-width`
![Screenshot 2022-03-21 111303](https://user-images.githubusercontent.com/39240820/159241324-ed4d40cc-8b76-4d88-9789-daef2aae5a65.png)

2022-03-21 10:30 UTC, mikethreels commented on index.html
> +    <div><img src="images/geometry.png" alt="menu"></div>
- [ ] this `img` tag should be removed because, decorations are always background images, not `img` tags. please include this.

2022-03-21 10:30 UTC, mikethreels commented on README.md
> +
- [ ] please remove the live demo link if it is not used

2022-03-21 10:30 UTC, mikethreels commented on README.md
> +### Deployment
- [ ] it is good that you used[ the Microverse template](https://github.com/microverseinc/readme-template) for your readme file however please make sure to fill it in with the information related to you and your project. keep in mind that all sections in template are mandatory apart from the "live demo", "Run tests" and "Deployment" (unless these are a requirement in a specific project)

2022-03-21 10:30 UTC, mikethreels commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] the link to the license is not working as expected, please have another look at [the Microverse template](https://github.com/microverseinc/readme-template) for an example of how it is expected to work.

2022-03-21 15:28 UTC, ShoiraTa requested changes
STATUS: CHANGES REQUIRED 🟡 
----
Hi @WillyStorm ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are some issues that you still need to work on to go to the next project but you are almost there!

![woohoo-youre-almost](https://user-images.githubusercontent.com/77038610/154921145-1f7bb8f6-c843-4ba5-a534-6b840c600558.jpeg)


 ## Required Changes  :recycle: 

_Check the comments under the review._ 

## Optional suggestions

- [ ] Optional: please make sure to always add a Pull Request description, you can easily update this pull request and add a description by clicking on three dots on the right side.
<img width="842" alt="Screenshot 2022-03-21 at 19 24 08" src="https://user-images.githubusercontent.com/77038610/159293817-c0b7ab4c-dcb0-451b-942e-4b191b557601.png">

 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-21 15:28 UTC, ShoiraTa commented on README.md
> +### Usage
- [ ] As the previous reviewer mentioned, please make sure to fill it in with the information related to you and your project. 😉

2022-03-21 15:28 UTC, ShoiraTa commented on README.md
> +
- [ ] OPTIONAL: I recommend adding a brief description about the project, remember that REAMDE is the first document that introduces your hard-work  to other users 💯

2022-03-21 15:28 UTC, ShoiraTa commented on README.md
> +
- [ ] As the previous reviewer mentioned, I recommend to delete this message and replace it with steps to setup the project 😺

2022-03-21 15:28 UTC, ShoiraTa commented on index.html
> +    <link rel="stylesheet" href="/style.css">
- [ ] I noticed that the stylesheet still does not open, this is a common error that occurs if you do not add `./` before the url. As the previous reviewer mentioned, you can either remove the forward-slash `(/)` from the href, or add `./`. I recorded video to show the issue and solutions:

https://user-images.githubusercontent.com/77038610/159292966-799296f3-dbb6-4885-bb8e-3f02bd5f4c13.mp4

2022-03-21 15:28 UTC, ShoiraTa commented on index.html
> +            <button type="button" class="rectangle">Start collaboration</button>
- [ ] OPTIONAL: I recommend deleting the default border around the button by setting `border: none`

2022-03-21 15:28 UTC, ShoiraTa commented on index.html
> +            <h1>Charlie<br>Giorgania</h1>
- [ ] OPTIONAL: The content of this section had to be aligned with `flexbox`. Try to make align it with `flexbox` 💪🏻

2022-03-22 10:44 UTC, Rustamxon7 approved these changes
## Hello @WillyStorm 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉, 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-22 11:20 UTC, merged